#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gomicro/influxdb ] || mkdir -p /var/log/gomicro/influxdb

# tell svlogd to drop the stdout into our custom location
cd /var/log/gomicro/influxdb
exec svlogd -v -ttt /var/log/gomicro/influxdb
