#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gomicro/narc ] || mkdir -p /var/log/gomicro/narc

# tell svlogd to drop the stdout into our custom location
cd /var/log/gomicro/narc
exec svlogd -v -ttt /var/log/gomicro/narc
