#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# This hook will export the data to the new members while the service is offline
payload[:members].each do |member|

  # export influxdb
  execute "send diff data to new member" do
    command <<-EOF
      rsync \
        --delete \
        -a \
        /var/db/influxdb/. \
        #{member[:local_ip]}:/var/db/influxdb/
    EOF
  end

  # export pulse
  execute "send diff data to new member" do
    command <<-EOF
      rsync \
        --delete \
        -a \
        /var/db/pulse/. \
        #{member[:local_ip]}:/var/db/pulse/
    EOF
  end
end
