#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

if File.exist?('/opt/gonano/etc/narc.conf')
  # create the runit definitions for narc
  directory '/etc/service/narc' do
    recursive true
  end

  directory '/etc/service/narc/log' do
    recursive true
  end

  hook_file '/etc/service/narc/log/run' do
    source 'runit/narc-log'
    mode 0755
  end

  hook_file '/etc/service/narc/run' do
    source 'runit/narc'
    mode 0755
  end

  service 'narc' do
    action :enable
  end
end

# create the runit definitions for influxdb
directory '/etc/service/influxdb' do
  recursive true
end

directory '/etc/service/influxdb/log' do
  recursive true
end

hook_file '/etc/service/influxdb/log/run' do
  source 'runit/influxdb-log'
  mode 0755
end

hook_file '/etc/service/influxdb/run' do
  source 'runit/influxdb'
  mode 0755
end

service 'influxdb' do
  action :enable
end

# create the runit definitions for pulse
directory '/etc/service/pulse' do
  recursive true
end

directory '/etc/service/pulse/log' do
  recursive true
end

hook_file '/etc/service/pulse/log/run' do
  source 'runit/pulse-log'
  mode 0755
end

hook_file '/etc/service/pulse/run' do
  source 'runit/pulse'
  mode 0755
end

service 'pulse' do
  action :enable
end
